### ISSUE TITLE
rev 2.0 on kitspace

### ISSUE THREAD

**Issue by ianabc** [Open-Gamma-Project/SiPM-Carrier-Board#3]
Are the Rev. 2.0 boards available on kitspace? When I click through the images and [inspect gerber link](https://tracespace.io/view/?boardUrl=https://kitspace.org/boards/github.com/OpenGammaProject/MicroFC-SiPM-Carrier-Board/MicroFC-SiPM-Carrier-Board-87d711a-gerbers.zip) seem to be for the Rev. 1.3 boards

**Comment by NuclearPhoenixx** [comment]
Yes, you're right. I'm really sorry for the inconvenience, but there is nothing I can do. Kitspace does have some problems with that and it looks like they won't be fixed until Kitspace-v2 launches some time in the future. I've already created an issue with them, so have a look at that too if you're interested: https://github.com/kitspace/kitspace/issues/416

I'm closing this issue since it's not really an issue related to the repo.
